### ISSUE TITLE
encoding detection breaks in locale "C" with UTF-8 source files

### ISSUE THREAD

**Issue by cabo** [YorickPeterse/ruby-lint#154]
Since Ruby 2.0, source files are UTF-8 by default.

ruby-lint breaks with that in locale "C":

```
...lib/ruby/gems/2.2.0/gems/parser-2.2.2.6/lib/parser/source/buffer.rb:157:in `source=': invalid byte sequence in US-ASCII (EncodingError)
	from ...lib/ruby/gems/2.2.0/gems/ruby-lint-2.0.4/lib/ruby-lint/parser.rb:40:in `parse'
	from ...lib/ruby/gems/2.2.0/gems/ruby-lint-2.0.4/lib/ruby-lint/runner.rb:78:in `parse_file'
```

The reason is that File.read(file).encoding yields US-ASCII in locale "C".  reencode_string takes that for face value instead of properly substituting UTF-8.  (The logic in there is somewhat surprising -- clearly any source file without an encoding comment is UTF-8, independent of what File.read says.)

**Comment by YorickPeterse** [comment]
ruby-lint itself doesn't care for encodings, and the error seems to originate from within the [parser](https://github.com/whitequark/parser) Gem, not ruby-lint. The workaround is quite simple: don't set your encoding to something that is not UTF8 compatible. There's no reason to use "C" as the locale.

**Comment by cabo** [comment]
Yes, the workaround is obvious (so obvious that I obviously did not mention it).
Making ruby-lint useless on systems that happen to configured with locale="C" still is not so great.
More generally, depending on the locale of the system for the semantics of a Ruby program is not an acceptable way to interpret that Ruby program.
Apparently, I need to cook up a test case for the parser Gem and file an issue there...
