### ISSUE TITLE
Gemfile support?

### ISSUE THREAD

**Issue by Pitometsu** [YorickPeterse/ruby-lint#157]
```
$ ruby-lint ./Gemfile
Gemfile: error: line 1, column 1: undefined method source
Gemfile: error: line 2, column 1: undefined method ruby
Gemfile: error: line 9, column 1: undefined method gem
(...)
```

**Comment by YorickPeterse** [comment]
ruby-lint has no understanding of how Gemfiles work. See https://github.com/YorickPeterse/ruby-lint/issues/52 and https://github.com/YorickPeterse/ruby-lint/issues/129 for more information. Please also provide meaningful tickets with what you expected to happen, a way to reproduce the problem, etc.
