### ISSUE TITLE
Feature request: emacs grep-like output

### ISSUE THREAD

**Issue by mcampbell** [YorickPeterse/ruby-lint#165]
How hard would it be to add a CLI option to output in a manner that emacs could grok it in a `*grep*` or `*grep-find*` buffer manner?  This would make it easy for (emacs, at least; possibly others) to run this tool, and have the IDE/editor automatically navigate to the offending line.

**Comment by YorickPeterse** [comment]
I have no idea what the output would be so I can't comment on that, but adding output formatters in general isn't too hard (e.g. https://github.com/YorickPeterse/ruby-lint/blob/master/lib/ruby-lint/presenter/syntastic.rb).

**Comment by mcampbell** [comment]
Thanks Yorick

Would you mind if I took a stab and did a PR?  My ruby isn't awesome, but I might be able to figure this out with your pointer as to where to start.

Thanks!

**Comment by YorickPeterse** [comment]
@mcampbell Feel free to do so.

**Comment by mvidner** [comment]
I think this is resolved since version 2.2.0 has been released, right?

**Comment by YorickPeterse** [comment]
@mvidner Ah yes, thanks for reminding.
