### ISSUE TITLE
Exit codes

### ISSUE THREAD

**Issue by mensfeld** [YorickPeterse/ruby-lint#197]
When I use ruby-lint and I don't have any errors, my exit-code is 0 which is good, when I have some errors I get 1 but the same happens when ruby-lint crashes (also 1), so I don't have a way to distinguish this cases.

**Comment by YorickPeterse** [comment]
There isn't really any meaningful signal beyond `1` that I'm aware of that can be used to signal an error due to a crash. Your best bet is to check if the output contains anything that resembles data from ruby-lint  reports.
